baseURL: "https://miheerdewaskar.com"
theme: hugo-apero
languageCode: en
title: Miheer Dewaskar
author: Miheer Dewaskar
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily:  EB Garamond
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/miheerdew
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/DewMiheer
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0002-7672-2531
    - icon: linkedin
      icon_pack: fab
      url: https://www.linkedin.com/in/miheer-dewaskar-a6b3a511a/
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  header:
    - name: About
      title: About me
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
